### ISSUE TITLE
PokeDex View

### ISSUE THREAD

**Issue by simibac** [PokeMate/frontend#1]
## User Story
As a user, I want to see available Pokemons so that I can sort them according to their Pokemon generation or their type.

## Description
This is best known as the PokeDex where all available Pokemons can be found. This view is always sorted by the PokeDex Id. 

## Tasks
- [ ] View for displaying every existing Pokemon
- [ ] TabView for Pokemons categorized by Generation or Type
- [ ] List is sorted by PokeDex Id
- [ ] List can be searched with a search bar
- [ ] View adapts to screen size
- [ ] Newly created Pokemons are shown in a new (Generation X) Tab
