### ISSUE TITLE
DateOutcome view

### ISSUE THREAD

**Issue by simibac** [PokeMate/frontend#14]
## User Story
As a user, I want to see the outcome of a date so that I know if the selected combination is good or not.

## Description
This view indicates if the combination of two Pokemons fits well.  
![Screenshot 2020-03-29 at 13 14 01](https://user-images.githubusercontent.com/15369592/78535563-ad32db80-77ec-11ea-8991-42e0a2da6293.png)

The time shows how long it roughly takes to generate the image for the baby Pokemon. 

The header is generated by the backend is generated from a list of funny sentences. See [wiki](https://github.com/PokeMate/backend/wiki/Endpoints#date-details) of backend.

## Tasks
- [x] View shows detail of a date
- [x] View works on different screen sizes
- [x] connect to API
