### ISSUE TITLE
Pokemon Detail View

### ISSUE THREAD

**Issue by simibac** [PokeMate/frontend#2]
## User Story
As a user, I want to see all the details to a selected Pokemons so that I can find detailed information about each individual Pokemon.

## Description
Information to be shown:
- name
- generation
- types
- fetish
- weight
- attraction to which elements (types)
- fertility rate
- attractiveness
- no-gos for mating partners

This detail view can be accessed from the PokeDex #1 or the Collection #4.

## Tasks
- [ ] View shows all the described information above
- [ ] View works on different screen sizes
- [ ] Button for quickly navigate to MatingView #3  with the selected Pokemon
