### ISSUE TITLE
Mating View

### ISSUE THREAD

**Issue by simibac** [PokeMate/frontend#3]
## User Stories
- As a user, I want to select two Pokemons for a date so that there is a chance that they mate and a new Pokemon is created. 
-  As a user, I want to find Pokemon combinations from my Pokemon collection so that the selected combination results in a higher probability of a successful copulation.

## Description
In this view two Pokemons can be selected from the Pokemon collection (by drag and drop?) such that they appear next to each other. 

## Tasks
- [ ] View shows the Pokemon collection
- [ ] View shows two placeholders where the Pokemons should be placed
- [ ] Pokemons from the collection can be selected and then appear in the free spots
- [ ] Button for mating the two selected Pokemons
- [ ] Warning if the not two Pokemons are selected
- [ ] Indicator for successful mating partners of the two selected Pokemons
