### ISSUE TITLE
Collection View

### ISSUE THREAD

**Issue by simibac** [PokeMate/frontend#4]
## User Story
As a user, I want to select a Pokemon from the PokeDex and add it to my collection so that it appears among my other Pokemons in my collection.

## Description
Players can select Pokemons from the PokeDex to their own collection. At some point this will not be free. However, as part of this project it will not cost any money. Looks similar to the PokeDex View #1.

## Tasks
- [ ] View for displaying every Pokemon in a player's collection
- [ ] TabView for Pokemons categorized by Generation or Type
- [ ] List is sorted by PokeDex Id
- [ ] List can be searched with a search bar
- [ ] View adapts to screen size
- [ ] Newly created Pokemons are shown in a new (Generation X) Tab
