### ISSUE TITLE
Project Maintenance

### ISSUE THREAD

**Issue by simibac** [PokeMate/frontend#6]
## User Story
As a developer, I want to have a wiki with detailed information about the setup instructions of the frontend application so that the project can be cloned and deployed on a different machine.

## Description
- The readme explains briefly how the application can be installed and deploy
- The wiki informs the people similar to the readme but in an extended form, such as the available views of the application etc.

## Tasks
- [ ] readme: instructions for setting up the environment
- [ ] readme: instructions for building and running the application
- [ ] readme: instructions for running the tests
- [ ] wiki: instructions for the design choices of each view
- [ ] .gitignore
