### ISSUE TITLE
PokeDex view

### ISSUE THREAD

**Issue by simibac** [PokeMate/frontend#7]
## User Story
As a user, I want to see available Pokemons so that I can sort them according to their Pokemon generation or their type.

## Description
This is best known as the PokeDex where all available Pokemons can be found. This view is always sorted by the PokeDex Id. 

## Tasks
- [x] View for displaying every existing Pokemon
- [x] ~~TabView for Pokemons categorized by Generation or Type~~
- [x] List is sorted by PokeDex Id
- [x] ~~List can be searched with a search bar~~
- [x] View adapts to screen size
- [x] Newly created Pokemons are shown in a new (Generation X) Tab
