### ISSUE TITLE
PokemonDetail view

### ISSUE THREAD

**Issue by simibac** [PokeMate/frontend#8]
## User Story
As a user, I want to see all the details to a selected Pokemons so that I can find detailed information about each individual Pokemon.

## Description
Information to be shown:
- name
- generation
- types
- fetish
- weight
- attraction to which elements (types)
- fertility rate
- attractiveness
- no-gos for mating partners

This detail view can be accessed from the PokeDex #1 or the Collection #4.

## Tasks
- [x] View shows all the described information above
- [x] View works on different screen sizes
- [x] Display average rating for each pokemon
- [x] Allow direct rating within the details view for each pokemon (not just newly created ones)
- [x] Button for quickly navigate to MatingView #3  with the selected Pokemon  
- [x] connect to API

**Comment by simibac** [comment]
actual data for some properties such as fetishes is still missing

**Comment by simibac** [comment]
#27
