### ISSUE TITLE
Mating view

### ISSUE THREAD

**Issue by Lochindaal** [PokeMate/frontend#9]
## User Stories
- As a user, I want to select two Pokemons for a date so that there is a chance that they mate and a new Pokemon is created. 
-  As a user, I want to find Pokemon combinations from my Pokemon collection so that the selected combination results in a higher probability of a successful copulation.

## Description
In this view two Pokemons can be selected from the Pokemon collection (by drag and drop?) such that they appear next to each other. 
<img width="1109" alt="mating-view" src="https://user-images.githubusercontent.com/15369592/78535330-41507300-77ec-11ea-8101-7813ad96b91d.png">

## Tasks
- [x] View shows the Pokemon collection
- [x] View shows two placeholders where the Pokemons should be placed
- [x] Pokemons from the collection can be selected and then appear in the free spots
- [x] Button for mating the two selected Pokemons
- [x] Warning if the not two Pokemons are selected
- [x] ~~Indicator for successful mating partners of the two selected Pokemons~~
- [x] connect to API

**Comment by simibac** [comment]
actual api call is still missing
